# Module 2: Data Cleaning and Validation

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load Dataset

df = pd.read_csv("../data/raw/Nassau Candy Distributor.csv")

In [3]:
# Display Dataset

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [5]:
# Check data types

df.dtypes

Row ID              int64
Order ID              str
Order Date            str
Ship Date             str
Ship Mode             str
Customer ID         int64
Country/Region        str
City                  str
State/Province        str
Postal Code           str
Division              str
Region                str
Product ID            str
Product Name          str
Sales             float64
Units               int64
Gross Profit      float64
Cost              float64
dtype: object

In [7]:
# Convert Order Date and Ship Date into datetime format

df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    dayfirst=True
)

df["Ship Date"] = pd.to_datetime(
    df["Ship Date"],
    dayfirst=True
)

In [9]:
df.dtypes

Row ID                     int64
Order ID                     str
Order Date        datetime64[us]
Ship Date         datetime64[us]
Ship Mode                    str
Customer ID                int64
Country/Region               str
City                         str
State/Province               str
Postal Code                  str
Division                     str
Region                       str
Product ID                   str
Product Name                 str
Sales                    float64
Units                      int64
Gross Profit             float64
Cost                     float64
dtype: object

In [10]:
# Check missing values

df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [11]:
# Check duplicate records

df.duplicated().sum()

np.int64(0)

In [12]:
# Remove duplicate rows

df = df.drop_duplicates()

In [13]:
# Calculate Shipping Lead Time

df["Shipping Lead Time"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [14]:
df[["Order Date","Ship Date","Shipping Lead Time"]].head()

  Order Date  Ship Date  Shipping Lead Time
0 2024-01-03 2026-06-30                 909
1 2024-01-04 2026-07-01                 909
2 2024-01-04 2026-07-01                 909
3 2024-01-04 2026-07-01                 909
4 2024-01-05 2026-07-05                 912

In [15]:
# Find invalid lead times

df[df["Shipping Lead Time"] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost, Shipping Lead Time]
Index: []

In [16]:
# Remove negative lead times

df = df[df["Shipping Lead Time"] >= 0]

In [17]:
df.shape

(10194, 19)

In [18]:
# Save cleaned dataset

df.to_csv("../data/processed/cleaned_dataset.csv", index=False)

### Observation

- Date columns converted successfully.
- Shipping Lead Time calculated.
- Invalid lead times removed.
- Clean dataset saved for further analysis.