# Module 4: Route Definition and Aggregation

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load Feature Engineered Dataset

df = pd.read_csv("../data/processed/feature_engineered_dataset.csv")

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,...,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Shipping Lead Time,Factory,Factory_to_State,Factory_to_Region
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909,Wicked Choccy's,Wicked Choccy's → Texas,Wicked Choccy's → Interior
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909,Wicked Choccy's,Wicked Choccy's → Illinois,Wicked Choccy's → Interior
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909,Lot's O' Nuts,Lot's O' Nuts → Illinois,Lot's O' Nuts → Interior
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912,Wicked Choccy's,Wicked Choccy's → Pennsylvania,Wicked Choccy's → Atlantic

In [4]:
# Route-wise shipment count
route_count = (
    df.groupby("Factory_to_State")
      .size()
      .reset_index(name="Shipment Count")
)

route_count.head()

                   Factory_to_State  Shipment Count
0           Lot's O' Nuts → Alabama              34
1           Lot's O' Nuts → Alberta              16
2           Lot's O' Nuts → Arizona             111
3          Lot's O' Nuts → Arkansas              31
4  Lot's O' Nuts → British Columbia              18

In [5]:
# Average Lead Time
avg_lead_time = (
    df.groupby("Factory_to_State")["Shipping Lead Time"]
      .mean()
      .reset_index(name="Average Lead Time")
)

avg_lead_time.head()

                   Factory_to_State  Average Lead Time
0           Lot's O' Nuts → Alabama        1295.205882
1           Lot's O' Nuts → Alberta        1273.875000
2           Lot's O' Nuts → Arizona        1306.198198
3          Lot's O' Nuts → Arkansas        1285.354839
4  Lot's O' Nuts → British Columbia        1273.777778

In [6]:
# Route Performence Summary
route_summary = (
    df.groupby("Factory_to_State")
      .agg(
          Shipment_Count=("Shipping Lead Time", "count"),
          Average_Lead_Time=("Shipping Lead Time", "mean"),
          Min_Lead_Time=("Shipping Lead Time", "min"),
          Max_Lead_Time=("Shipping Lead Time", "max")
      )
      .reset_index()
)

route_summary.head()

,Factory_to_State,Shipment_Count,Average_Lead_Time,Min_Lead_Time,Max_Lead_Time
0,Lot's O' Nuts → Alabama,34,1295.205882,906,1642
1,Lot's O' Nuts → Alberta,16,1273.875000,909,1640
2,Lot's O' Nuts → Arizona,111,1306.198198,904,1642
3,Lot's O' Nuts → Arkansas,31,1285.354839,908,1642
4,Lot's O' Nuts → British Columbia,18,1273.777778,906,1640

In [7]:
# Ship Mode Count
ship_mode_summary = (
    df.groupby("Ship Mode")
      .size()
      .reset_index(name="Total Shipments")
)

ship_mode_summary

        Ship Mode  Total Shipments
0     First Class             1548
1        Same Day              547
2    Second Class             1979
3  Standard Class             6120

In [8]:
# Average Lead Time by Ship Mode
ship_mode_performance = (
    df.groupby("Ship Mode")["Shipping Lead Time"]
      .mean()
      .reset_index(name="Average Lead Time")
)

ship_mode_performance

        Ship Mode  Average Lead Time
0     First Class        1338.275840
1        Same Day        1333.442413
2    Second Class        1323.845376
3  Standard Class        1314.334641

In [9]:
# Save Results
route_summary.to_csv(
    "../data/processed/route_summary.csv",
    index=False
)

ship_mode_performance.to_csv(
    "../data/processed/ship_mode_performance.csv",
    index=False
)

### Observation

- Route-wise shipment statistics generated.
- Average lead time calculated.
- Ship mode performance analyzed.
- Summary files saved successfully.